### ISSUE TITLE
gleam run fails with p5 is not defined error

### ISSUE THREAD

**Issue by gamecubate** [Acepie/p5js_gleam#1]
Hi.

Invoking `gleam run --target javascript` fails with a `ReferenceError: p5 is not defined` message.

```
file:///build/dev/javascript/p5js_gleam/p5js_ffi.mjs:6
  new p5(function (p) {
  ^

ReferenceError: p5 is not defined
    at Module.startSketch (file:///build/dev/javascript/p5js_gleam/p5js_ffi.mjs:6:3)
```

Tested with gleam 1.1.0.

**Comment by Acepie** [comment]
Hi :D the library provides the bindings and an interface but doesn't provide p5js in scope itself since there are a number of different ways to do that and people might have preferences depending on how they are running their app. In the examples https://github.com/Acepie/p5js_gleam/blob/main/examples/minimal/dist/index.html#L8 I include the p5js library from a cdn in the html itself. Alternatively, if you are using a bundler you could add the npm package/file into the bundle itself though you'd need to do a bit of work to get that working since I haven't tried it myself

**Comment by gamecubate** [comment]
That makes perfect sense. Thanks. :)
