### ISSUE TITLE
Plan for the Repos? Need help?

### ISSUE THREAD

**Issue by Orasund** [Acepie/p5js_gleam#2]
Hi there.

> TLDR; I'm working on my own P5js bindings and wanted to ask If you'd like to collaborate

I wanted to do some p5js stuff and saw your package, but your package needing bun and coming with a "game engine" put me off.

So I implemented my own version:
* [Js file](https://github.com/Orasund/gleam-playground/blob/main/genart_lambda_leaf/src/p5Module.mjs)
* [gleam files](https://github.com/Orasund/gleam-playground/tree/main/genart_lambda_leaf/src/p5js_bindings)

My biggest change is that I expose the P5 bindings globally, so that I don't have to pass them around.

**I was wondering if you'd like to join forces and let me help out in your repository**

I have a couple of long term plans:
* Setup a Github Action that reads the types out of the [original p5.js source files](https://github.com/processing/p5.js/tree/main/src) and generates the bindings for it
* Look into WebGL and if there are nice ways of writing it in Gleam
* Have a very light set of functional primitives that allow a declarative coding style.

Does this align with your plans?

**Comment by Acepie** [comment]
Hi :D yeah I'd be happy to accept contributions/collaborate. 

Writing up a better way to generate the bindings would be cool and if you have ideas for that then great. The current implementation is only a bun script because of https://github.com/Acepie/p5js_gleam/blob/main/scripts/generate_p5.ts#L190-L191 the 2 lines that write to a file so I'd be happy to swap to something else but haven't had a reason to. Something that parses the p5js source and exposes bindings would be cool but probably really hard to implement in a way that is typesafe since p5js is pretty explicitly loose with many ways of doing things. Thats why instead I went with something more tailored/limited with more clear intent. 

The "game engine" aspect though is essentially just sketch setup https://github.com/Acepie/p5js_gleam/blob/main/src/p5js_ffi.mjs#L3-L48 so i don't think that will ever be changing. Part of the point of the package was to encourage a functional style/architecture for users so the game engine is just setting up the sketch in a way to encourage update functions to go from state -> state and a renderer.

That being said, I think writing up primitives that further support a more declarative style instead of the current direct imperative bindings would be a cool addition/allow us to make a more tailored subset to encourage good practices.

As for WebGL, I think it would be cool but haven't had any time to look into it but i do think it would be an awesome addition

**Comment by Orasund** [comment]
Ok nice. I'll start with the generator then.

I'll try to do a very small prove of concept. I've done something similar before with [Orasund/elm-html-style](https://github.com/Orasund/elm-html-style).

**Comment by Orasund** [comment]
Ok, so [here is my POC](https://github.com/Orasund/gleam-playground/tree/main/p5js_generator):
* [js output](https://github.com/Orasund/gleam-playground/blob/main/p5js_generator/output.js)
* [gleam output](https://github.com/Orasund/gleam-playground/blob/main/p5js_generator/output.gleam)

For my POC I had to cut a couple of corners.
* Only looked at a single file (2d_primitives.js)
* Used of-the-shelf products that might not be useful for the full implementation
* Ignored the Constant type for arc
* Ignored the p5.Vector type for point
* Forgot to snake case the parameters >.<

So yeah, this is definitely possible. I'd like to have an MVP as soon as possible, and then add missing features over time.

**Comment by Orasund** [comment]
Quick Status update:

I opened MR #3 for simplifying the API by exposing `p` to the module.

Created a generator in Gleam that can support most of the common use cases.
* Overloaded Operations are differentiated by indexes
    ```
    export const line1 = (x1, y1, x2, y2) => p5.line(x1, y1, x2, y2)

    export const line2 = (x1, y1, z1, x2, y2, z2) => p5.line(x1, y1, z1, x2, y2, z2)
    ```
* Constants can't be generated automatically. For example:
    ```
    /**
     * CSS named colors.
     */
    const namedColors = {
      aliceblue: '#f0f8ff',
      antiquewhite: '#faebd7',
      aqua: '#00ffff',
      aquamarine: '#7fffd4',
      ..
    }
    ```
    
Also, I think instead of using SketchConfig as an opaque type, it could be a simple record. As far as I can tell, it's just the Assets that are different between the Variants. Is there a reason why they are not optional?

**Comment by Acepie** [comment]
I don't think using indices for overloaded operations is a good idea for a reusable library. We want it to be clear to users what each function does and seeing the same function with different indices would be confusing. I would prefer to either explicitly choose 1 version intentionally or if we want to support every overload, have the name make it clear what the variation is.

The reason the sketchconfig is an opaque type is to make the api for creating a sketch not require users to write a bunch of "event: None" for every single event handler. Since in gleam you have to specify every field to a constructor even if its optional, the user would still have to write each None out. Hence instead we expose a builder pattern that needs the required handlers and provide functions to add additional builders. We could make it not opaque but it would be a pain to use in practice so I'd rather keep it as is so people don't try to use it

**Comment by Orasund** [comment]
You got some good points.

we can't choose one version because it's not always clear what to choose:

```
export const rect1 = (x, y, w, h, detail_x, detail_y) => p5.rect(x, y, w, h, detail_x, detail_y)

export const rect2 = (x, y, w, h, tl, tr, br, bl) => p5.rect(x, y, w, h, tl, tr, br, bl)
```

Regarding the opaque type, I would also use a builder pattern. It's just that I would use a record instead of a custom type. But maybe I've overlooked something. I'll probably just have to implement my own version to see what the tradeoffs are.

So I think I just have to build a more fleshed out version to be able to compare with your current implementation.

**Comment by Orasund** [comment]
Hi, I think it's probably best if I just publish my own version.

It essentially comes down to the question if the p5 instance should be passed along or not.

My generator can produce both variance, but to maintain a set of declarative helper function, one has to choose between one of them. And I believe the version without the p5 instance is better.

Just wanted to let you know.

**Comment by Acepie** [comment]
Perfectly understandable :D thanks for letting me know
